import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

 export const products = [
  {
    _id: uuid(),
    title: "UNISEX REEBOK RUNNING ZIG KINETICA II SHOES",
    image: "/resource/product/running/UNISEX-ADULTS REEBOK CLASSICS LEATHER VEGAN SHOES.jpg",
    brand: "Reebok",
    price: 9999.00,
    discount: "20%",
    gender: "Women",
    discountedPrice: 7999.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "MEN'S REEBOK RUNNING LIQUIFECT 180 3.0 SHOES",
    image: "/resource/product/running/MEN'S REEBOK RUNNING LIQUIFECT 180 3.0 SHOES.jpg",
    brand: "Reebok",
    price: 6599.00,
    discount: "30%",
    gender: "Men",
    discountedPrice: 4619.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "UNISEX-ADULTS REEBOK CLASSICS LEATHER VEGAN SHOES",
    image: "/resource/product/running/UNISEX-ADULTS REEBOK CLASSICS LEATHER VEGAN SHOES.jpg",
    brand: "Reebok",
    price: 6599.00,
    discount: "40%",
    gender: "Men",
    discountedPrice: 3959.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "MEN'S REEBOK FITNESS BILLINGTON SHOES",
    image: "/resource/product/running/MEN'S REEBOK FITNESS BILLINGTON SHOES.jpg",
    brand: "Reebok",
    price: 3299.00,
    discount: "60%",
    gender: "Women",
    discountedPrice: 1320.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "MEN'S REEBOK RUNNING LIQUIFECT 90 SHOES",
    image: "/resource/product/running/MEN'S REEBOK RUNNING LIQUIFECT 90 SHOES.jpg",
    brand: "Reebok",
    price: 5999.00,
    discount: "40%",
    gender: "Men",
    discountedPrice: 3599.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "MEN REEBOK FITNESS ZIG DYNAMICA 2 SHOES",
    image: "/resource/product/running/MEN REEBOK FITNESS ZIG DYNAMICA 2 SHOES.jpg",
    brand: "Reebok",
    price: 7599.00,
    discount: "",
    gender: "Men",
    discountedPrice: 7599.00,
    categoryName: "Running",
    rating: 4
  },
  
  {
    _id: uuid(),
    title: "Nike React Infinity Run Flyknit 3",
    image: "/resource/product/running/Nike React Infinity Run Flyknit 3.jpg",
    brand: "Nike",
    price: 13599.00,
    discount: "",
    gender: "Men",
    discountedPrice: 13599.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike Air Zoom Vomero 16",
    image: "/resource/product/running/Nike Air Zoom Vomero 16.jpg",
    brand: "Nike",
    price: 13495.00,
    discount: "25%",
    gender: "Men",
    discountedPrice: 10121.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike Air Zoom Pegasus 38 FlyEase",
    image: "/resource/product/running/Nike Air Zoom Pegasus 38 FlyEase.jpg",
    brand: "Nike",
    price: 9995.00,
    discount: "19%",
    gender: "Men",
    discountedPrice: 7997.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike Air Zoom Pegasus 38",
    image: "/resource/product/running/Nike Air Zoom Pegasus 38.jpg",
    brand: "Nike",
    price: 9995.00,
    discount: "19%",
    gender: "Men",
    discountedPrice: 7997.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike ZoomX Invincible Run Flyknit",
    image: "/resource/product/running/Nike ZoomX Invincible Run Flyknit.jpg",
    brand: "Nike",
    price: 16595.00,
    discount: "",
    gender: "Men",
    discountedPrice: 16595.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike Pegasus Trail 3 GORE-TEX",
    image: "/resource/product/running/Nike Pegasus Trail 3 GORE-TEX.jpg",
    brand: "Nike",
    price: 14495.00,
    discount: "25%",
    gender: "Men",
    discountedPrice: 10871.00,
    categoryName: "Running",
    rating: 4
  },
  
  
  {
    _id: uuid(),
    title: "one8 Virat Kohli Softride Premier Men's Running Shoes",
    image: "/resource/product/running/one8 Virat Kohli Softride Premier Men's Running Shoes.jpg",
    brand: "Puma",
    price: 6999.00,
    discount: "",
    gender: "Women",
    discountedPrice: 6999.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Equate SL Running Shoes",
    image: "/resource/product/running/Equate SL Running Shoes.jpg",
    brand: "Puma",
    price: 5999.00,
    discount: "30%",
    gender: "Men",
    discountedPrice: 4199.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Aviator Unisex Running Shoes",
    image: "/resource/product/running/Aviator Unisex Running Shoes.jpg",
    brand: "Puma",
    price: 7999.00,
    discount: "20%",
    gender: "Men",
    discountedPrice: 6399.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Leader VT Tech Running Shoes",
    image: "/resource/product/running/Leader VT Tech Running Shoes.jpg",
    brand: "Puma",
    price: 5999.00,
    discount: "20%",
    gender: "Men",
    discountedPrice: 4799.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Electrify Nitro Turn Men's Shoes",
    image: "/resource/product/running/Electrify Nitro Turn Men's Shoes.jpg",
    brand: "Puma",
    price: 9999.00,
    discount: "35%",
    gender: "Men",
    discountedPrice: 6499.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "NRGY Comet Unisex Running Shoes",
    image: "/resource/product/running/NRGY Comet Unisex Running Shoes.jpg",
    brand: "Puma",
    price: 4499.00,
    discount: "30%",
    gender: "Men",
    discountedPrice: 3149.00,
    categoryName: "Running",
    rating: 4
  },
  
  {
    _id: uuid(),
    title: "Ultimashow Shoes",
    image: "/resource/product/running/Ultimashow Shoes.jpg",
    brand: "Adidas",
    price: 4999.00,
    discount: "50%",
    gender: "Men",
    discountedPrice: 2499.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Turbo Glide",
    image: "/resource/product/running/Turbo Glide.jpg",
    brand: "Adidas",
    price: 3599.00,
    discount: "40%",
    gender: "Men",
    discountedPrice: 2159.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Ultraboost 22",
    image: "/resource/product/running/Ultraboost 22.jpg",
    brand: "Adidas",
    price: 17999.00,
    discount: "",
    gender: "Men",
    discountedPrice: 17999.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Amaz-Runner",
    image: "/resource/product/running/Amaz-Runner.jpg",
    brand: "Adidas",
    price: 6599.00,
    discount: "50%",
    gender: "Men",
    discountedPrice: 3299.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Adi Rush",
    image: "/resource/product/running/Adi Rush.jpg",
    brand: "Adidas",
    price: 4299.00,
    discount: "40%",
    gender: "Men",
    discountedPrice: 2579.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Pictor",
    image: "/resource/product/running/Pictor.jpg",
    brand: "Adidas",
    price: 4799.00,
    discount: "50%",
    gender: "Men",
    discountedPrice: 2399.00,
    categoryName: "Running",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Proxima",
    image: "/resource/product/running/Proxima.jpg",
    brand: "Adidas",
    price: 4999.00,
    discount: "50%",
    gender: "Men",
    discountedPrice: 2499.00,
    categoryName: "Running",
    rating: 4
  },
  
  
  {
    _id: uuid(),
    title: "Easy Vulc 2.0",
    image: "/resource/product/sneaker/Easy Vulc 2.0.jpg",
    brand: "Adidas",
    price: 4599.00,
    discount: "40%",
    gender: "Women",
    discountedPrice: 2759.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Grand Court SE",
    image: "/resource/product/sneaker/Grand Court SE.jpg",
    brand: "Adidas",
    price: 6599.00,
    discount: "40%",
    gender: "Men",
    discountedPrice: 3959.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "VS Pace",
    image: "/resource/product/sneaker/VS Pace.jpg",
    brand: "Adidas",
    price: 3999.00,
    discount: "",
    gender: "Men",
    discountedPrice: 3999.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Easy Vulc 2.0",
    image: "/resource/product/sneaker/Easy Vulc 2.0.jpg",
    brand: "Adidas",
    price: 12495.00,
    discount: "",
    gender: "Men",
    discountedPrice: 12495.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Court Smash",
    image: "/resource/product/sneaker/Court Smash.jpg",
    brand: "Adidas",
    price: 5599.00,
    discount: "50%",
    gender: "Men",
    discountedPrice: 2799.00,
    categoryName: "Sneaker",
    rating: 4
  },
  
  {
    _id: uuid(),
    title: "Nike Air Max Terrascape 90",
    image: "/resource/product/sneaker/Nike Air Max Terrascape 90.jpg",
    brand: "Nike",
    price: 10295.00,
    discount: "",
    gender: "Men",
    discountedPrice: 10295.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike Dunk High Retro SE",
    image: "/resource/product/sneaker/Nike Dunk High Retro SE.jpg",
    brand: "Nike",
    price: 10295.00,
    discount: "",
    gender: "Women",
    discountedPrice: 10295.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Jordan Series Mid",
    image: "/resource/product/sneaker/Jordan Series Mid.jpg",
    brand: "Nike",
    price: 8595.00,
    discount: "",
    gender: "Men",
    discountedPrice: 8595.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Air Jordan 1 Mid SE",
    image: "/resource/product/sneaker/Air Jordan 1 Mid SE.jpg",
    brand: "Nike",
    price: 11895.00,
    discount: "",
    gender: "Men",
    discountedPrice: 11895.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Nike Dunk Low By You",
    image: "/resource/product/sneaker/Nike Dunk Low By You.jpg",
    brand: "Nike",
    price: 10995.00,
    discount: "",
    gender: "Women",
    discountedPrice: 10995.00,
    categoryName: "Sneaker",
    rating: 4
  },
  
  {
    _id: uuid(),
    title: "Mirage Sport Go",
    image: "/resource/product/sneaker/Mirage Sport Go.jpg",
    brand: "Puma",
    price: 8999.00,
    discount: "",
    gender: "Men",
    discountedPrice: 8999.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Mirage Sport Layers",
    image: "/resource/product/sneaker/Mirage Sport Layers.jpg",
    brand: "Puma",
    price: 7999.00,
    discount: "",
    gender: "Men",
    discountedPrice: 7999.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Space Lab The NeverWorn",
    image: "/resource/product/sneaker/Space Lab The NeverWorn.jpg",
    brand: "Puma",
    price: 8000.00,
    discount: "20%",
    gender: "Men",
    discountedPrice: 6400.00,
    categoryName: "Sneaker",
    rating: 4
  },
  {
    _id: uuid(),
    title: "Slipstream Lo The NeverWorn",
    image: "/resource/product/sneaker/Slipstream Lo The NeverWorn.jpg",
    brand: "Puma",
    price: 8999.00,
    discount: "",
    gender: "Men",
    discountedPrice: 8999.00,
    categoryName: "Sneaker",
    rating: 4
  },
]