import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

 export const products = [
  {
      _id: "491dec22-6dfc-4c0d-9b93-a3b6b8d7b42d",
      title: "UNISEX REEBOK RUNNING ZIG KINETICA II SHOES",
      image: "/resource/product/running/UNISEX-ADULTS REEBOK CLASSICS LEATHER VEGAN SHOES.jpg",
      brand: "Reebok",
      price: 9999,
      discount: "20%",
      gender: "Women",
      discountedPrice: 7999,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "576180ce-4f41-48a8-a99d-a57816d32263",
      title: "MEN'S REEBOK RUNNING LIQUIFECT 180 3.0 SHOES",
      image: "/resource/product/running/MEN'S REEBOK RUNNING LIQUIFECT 180 3.0 SHOES.jpg",
      brand: "Reebok",
      price: 6599,
      discount: "30%",
      gender: "Men",
      discountedPrice: 4619,
      categoryName: "Running",
      rating: 4,
      images: [
        "https://content.shop4reebok.com/static/Product-H00869/Reebok_H00869_4.jpg",
        "https://content.shop4reebok.com/static/Product-H00869/Reebok_H00869_3.jpg"
      ]
  },
  {
      _id: "ea040898-ca1c-40ea-8049-7dabeab3dde7",
      title: "UNISEX-ADULTS REEBOK CLASSICS LEATHER VEGAN SHOES",
      image: "/resource/product/running/UNISEX-ADULTS REEBOK CLASSICS LEATHER VEGAN SHOES.jpg",
      brand: "Reebok",
      price: 6599,
      discount: "40%",
      gender: "Men",
      discountedPrice: 3959,
      categoryName: "Running",
      rating: 4,
      images: [
        "https://content.shop4reebok.com/static/Product-GW9962/reebok_GW9962_2.jpg",
        "https://content.shop4reebok.com/static/Product-GW9962/reebok_GW9962_5.jpg",
        "https://content.shop4reebok.com/static/Product-GW9962/reebok_GW9962_3.jpg"
      ]
  },
  {
      _id: "6f7f46de-b07f-4a0d-b8c3-6522c6cab937",
      title: "MEN'S REEBOK FITNESS BILLINGTON SHOES",
      image: "/resource/product/running/MEN'S REEBOK FITNESS BILLINGTON SHOES.jpg",
      brand: "Reebok",
      price: 3299,
      discount: "60%",
      gender: "Women",
      discountedPrice: 1320,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "eb17e7b9-4f1b-49d6-84cc-9c0ed18abf3c",
      title: "MEN'S REEBOK RUNNING LIQUIFECT 90 SHOES",
      image: "/resource/product/running/MEN'S REEBOK RUNNING LIQUIFECT 90 SHOES.jpg",
      brand: "Reebok",
      price: 5999,
      discount: "40%",
      gender: "Men",
      discountedPrice: 3599,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "823d40e3-2ff9-4e33-9ba0-54b3ff8716a6",
      title: "MEN REEBOK FITNESS ZIG DYNAMICA 2 SHOES",
      image: "/resource/product/running/MEN REEBOK FITNESS ZIG DYNAMICA 2 SHOES.jpg",
      brand: "Reebok",
      price: 7599,
      discount: "",
      gender: "Men",
      discountedPrice: 7599,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "2296dcde-0fb1-42e7-b0c0-377443858e06",
      title: "Nike React Infinity Run Flyknit 3",
      image: "/resource/product/running/Nike React Infinity Run Flyknit 3.jpg",
      brand: "Nike",
      price: 13599,
      discount: "",
      gender: "Men",
      discountedPrice: 13599,
      categoryName: "Running",
      rating: 4,
      images: [
        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/02c80f0d-e45c-48c1-944a-3ef642d2a868/react-infinity-run-flyknit-3-road-running-shoes-S5Srkq.png",
        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/dc7b3070-51f8-4ae8-b55f-7b35c3606f20/react-infinity-run-flyknit-3-road-running-shoes-S5Srkq.png"
      ]
  },
  {
      _id: "5063e8ff-8022-4f11-b37c-1d60a8c5c1a1",
      title: "Nike Air Zoom Vomero 16",
      image: "/resource/product/running/Nike Air Zoom Vomero 16.jpg",
      brand: "Nike",
      price: 13495,
      discount: "25%",
      gender: "Men",
      discountedPrice: 10121,
      categoryName: "Running",
      rating: 4,
      images: [
        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/95d9389d-5dc3-4284-84e7-a5aec84f5316/air-zoom-vomero-16-road-running-shoes-h0KMSg.png",
        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/974881b7-d15f-4e51-8672-1ccabdb8611b/air-zoom-vomero-16-road-running-shoes-h0KMSg.png",
        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/8acc93a3-9fa7-4648-9e9c-9b7422cf7b15/air-zoom-vomero-16-road-running-shoes-h0KMSg.png"
      ]
  },
  {
      _id: "007f9f70-bc00-4f35-8d36-16e986e17b69",
      title: "Nike Air Zoom Pegasus 38 FlyEase",
      image: "/resource/product/running/Nike Air Zoom Pegasus 38 FlyEase.jpg",
      brand: "Nike",
      price: 9995,
      discount: "19%",
      gender: "Men",
      discountedPrice: 7997,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "65d69753-0026-4c69-b608-8ee55a16824f",
      title: "Nike Air Zoom Pegasus 38",
      image: "/resource/product/running/Nike Air Zoom Pegasus 38.jpg",
      brand: "Nike",
      price: 9995,
      discount: "19%",
      gender: "Men",
      discountedPrice: 7997,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "945a1509-a030-4aad-b07a-182f359e4ca0",
      title: "Nike ZoomX Invincible Run Flyknit",
      image: "/resource/product/running/Nike ZoomX Invincible Run Flyknit.jpg",
      brand: "Nike",
      price: 16595,
      discount: "",
      gender: "Men",
      discountedPrice: 16595,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "d453f25b-1d3a-4a92-ab1d-fd938cf82601",
      title: "Nike Pegasus Trail 3 GORE-TEX",
      image: "/resource/product/running/Nike Pegasus Trail 3 GORE-TEX.jpg",
      brand: "Nike",
      price: 14495,
      discount: "25%",
      gender: "Men",
      discountedPrice: 10871,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "7175e585-261d-4a2d-b981-fc8af25d2c11",
      title: "one8 Virat Kohli Softride Premier Men's Running Shoes",
      image: "/resource/product/running/one8 Virat Kohli Softride Premier Men's Running Shoes.jpg",
      brand: "Puma",
      price: 6999,
      discount: "",
      gender: "Women",
      discountedPrice: 6999,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "481b53c4-87bf-4fcb-a2fa-1526e972970b",
      title: "Equate SL Running Shoes",
      image: "/resource/product/running/Equate SL Running Shoes.jpg",
      brand: "Puma",
      price: 5999,
      discount: "30%",
      gender: "Men",
      discountedPrice: 4199,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "67c437ce-5413-428a-88b8-4138eadb51a6",
      title: "Aviator Unisex Running Shoes",
      image: "/resource/product/running/Aviator Unisex Running Shoes.jpg",
      brand: "Puma",
      price: 7999,
      discount: "20%",
      gender: "Men",
      discountedPrice: 6399,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "f421721a-d6f7-4879-a7b3-1e260501b09b",
      title: "Leader VT Tech Running Shoes",
      image: "/resource/product/running/Leader VT Tech Running Shoes.jpg",
      brand: "Puma",
      price: 5999,
      discount: "20%",
      gender: "Men",
      discountedPrice: 4799,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "8dbb574a-8b27-4372-9445-009362c61c4d",
      title: "Electrify Nitro Turn Men's Shoes",
      image: "/resource/product/running/Electrify Nitro Turn Men's Shoes.jpg",
      brand: "Puma",
      price: 9999,
      discount: "35%",
      gender: "Men",
      discountedPrice: 6499,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "f4057a2b-2bd4-4cc6-a4cd-53a4fbc00363",
      title: "NRGY Comet Unisex Running Shoes",
      image: "/resource/product/running/NRGY Comet Unisex Running Shoes.jpg",
      brand: "Puma",
      price: 4499,
      discount: "30%",
      gender: "Men",
      discountedPrice: 3149,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "34829254-8556-4bd6-a27e-9a8c4453102a",
      title: "Ultimashow Shoes",
      image: "/resource/product/running/Ultimashow Shoes.jpg",
      brand: "Adidas",
      price: 4999,
      discount: "50%",
      gender: "Men",
      discountedPrice: 2499,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "392ebad2-4d5a-414e-82d5-05aff991929b",
      title: "Turbo Glide",
      image: "/resource/product/running/Turbo Glide.jpg",
      brand: "Adidas",
      price: 3599,
      discount: "40%",
      gender: "Men",
      discountedPrice: 2159,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "11098ec0-65f9-4e43-9252-0dd50062b726",
      title: "Ultraboost 22",
      image: "/resource/product/running/Ultraboost 22.jpg",
      brand: "Adidas",
      price: 17999,
      discount: "",
      gender: "Men",
      discountedPrice: 17999,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "07390ab2-d833-4de3-8a92-f05114877a70",
      title: "Amaz-Runner",
      image: "/resource/product/running/Amaz-Runner.jpg",
      brand: "Adidas",
      price: 6599,
      discount: "50%",
      gender: "Men",
      discountedPrice: 3299,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "7980e437-b35d-49fd-af48-15ad9473b91e",
      title: "Adi Rush",
      image: "/resource/product/running/Adi Rush.jpg",
      brand: "Adidas",
      price: 4299,
      discount: "40%",
      gender: "Men",
      discountedPrice: 2579,
      categoryName: "Running",
      rating: 4,
      id: "23",
      images: []
  },
  {
      _id: "3c1e584f-00fe-4a0d-95f4-ec0d9a71e229",
      title: "Pictor",
      image: "/resource/product/running/Pictor.jpg",
      brand: "Adidas",
      price: 4799,
      discount: "50%",
      gender: "Men",
      discountedPrice: 2399,
      categoryName: "Running",
      rating: 4,
      id: "24",
      images: []
  },
  {
      _id: "c9a6c626-dcc7-4983-a98d-eef468785a3c",
      title: "Proxima",
      image: "/resource/product/running/Proxima.jpg",
      brand: "Adidas",
      price: 4999,
      discount: "50%",
      gender: "Men",
      discountedPrice: 2499,
      categoryName: "Running",
      rating: 4,
      images: []
  },
  {
      _id: "03fa6de9-eba7-48c8-b38d-3558d177ec1e",
      title: "Easy Vulc 2.0",
      image: "/resource/product/sneaker/Easy Vulc 2.0.jpg",
      brand: "Adidas",
      price: 4599,
      discount: "40%",
      gender: "Women",
      discountedPrice: 2759,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "172a0aad-a66a-43ee-aeb9-ccbc71202faf",
      title: "Grand Court SE",
      image: "/resource/product/sneaker/Grand Court SE.jpg",
      brand: "Adidas",
      price: 6599,
      discount: "40%",
      gender: "Men",
      discountedPrice: 3959,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "1180731f-7555-4796-b00b-af9c47c12e50",
      title: "VS Pace",
      image: "/resource/product/sneaker/VS Pace.jpg",
      brand: "Adidas",
      price: 3999,
      discount: "",
      gender: "Men",
      discountedPrice: 3999,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "b3ca0445-66be-48bf-9370-9c05ad3dde4e",
      title: "Easy Vulc 2.0",
      image: "/resource/product/sneaker/Easy Vulc 2.0.jpg",
      brand: "Adidas",
      price: 12495,
      discount: "",
      gender: "Men",
      discountedPrice: 12495,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "d8c5550f-1444-497f-8ea0-703850684007",
      title: "Court Smash",
      image: "/resource/product/sneaker/Court Smash.jpg",
      brand: "Adidas",
      price: 5599,
      discount: "50%",
      gender: "Men",
      discountedPrice: 2799,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "a491b748-5a00-4308-b9af-f966b3ae2fe4",
      title: "Nike Air Max Terrascape 90",
      image: "/resource/product/sneaker/Nike Air Max Terrascape 90.jpg",
      brand: "Nike",
      price: 10295,
      discount: "",
      gender: "Men",
      discountedPrice: 10295,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "ce14f08b-5299-490b-8911-a7b625fe47ad",
      title: "Nike Dunk High Retro SE",
      image: "/resource/product/sneaker/Nike Dunk High Retro SE.jpg",
      brand: "Nike",
      price: 10295,
      discount: "",
      gender: "Women",
      discountedPrice: 10295,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "66bc0792-f800-46c6-a540-5eb918512c0a",
      title: "Jordan Series Mid",
      image: "/resource/product/sneaker/Jordan Series Mid.jpg",
      brand: "Nike",
      price: 8595,
      discount: "",
      gender: "Men",
      discountedPrice: 8595,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "8c3558f9-f994-4b36-956e-2829822f1748",
      title: "Air Jordan 1 Mid SE",
      image: "/resource/product/sneaker/Air Jordan 1 Mid SE.jpg",
      brand: "Nike",
      price: 11895,
      discount: "",
      gender: "Men",
      discountedPrice: 11895,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "850376ad-487c-4e40-bc9a-38a85ed7c183",
      title: "Nike Dunk Low By You",
      image: "/resource/product/sneaker/Nike Dunk Low By You.jpg",
      brand: "Nike",
      price: 10995,
      discount: "",
      gender: "Women",
      discountedPrice: 10995,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "7915abf3-6dbf-4b3a-a8bb-e93966e2751e",
      title: "Mirage Sport Go",
      image: "/resource/product/sneaker/Mirage Sport Go.jpg",
      brand: "Puma",
      price: 8999,
      discount: "",
      gender: "Men",
      discountedPrice: 8999,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "a3d2bd5a-d5a8-4f6b-9b37-cff98babd03b",
      title: "Mirage Sport Layers",
      image: "/resource/product/sneaker/Mirage Sport Layers.jpg",
      brand: "Puma",
      price: 7999,
      discount: "",
      gender: "Men",
      discountedPrice: 7999,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "06a2cd8b-0e95-467c-967a-3dddba9968be",
      title: "Space Lab The NeverWorn",
      image: "/resource/product/sneaker/Space Lab The NeverWorn.jpg",
      brand: "Puma",
      price: 8000,
      discount: "20%",
      gender: "Men",
      discountedPrice: 6400,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  },
  {
      _id: "781e3eb5-197f-47df-81ba-5c4c0f1d7be4",
      title: "Slipstream Lo The NeverWorn",
      image: "/resource/product/sneaker/Slipstream Lo The NeverWorn.jpg",
      brand: "Puma",
      price: 8999,
      discount: "",
      gender: "Men",
      discountedPrice: 8999,
      categoryName: "Sneaker",
      rating: 4,
      images: []
  }
]